### ISSUE TITLE
Memory leakage + Double-free issues

### ISSUE THREAD

**Issue by brandongohwh** [gopro/gpmf-parser#71]
Continuing from #50, I used a few existing mutated files on the compiled program on the latest commit 6d1e9fe25dc7e23193331affbad57e7f87c2ee69 and found 2 more issues.

The 2 main issues are mainly,

1. Memory leakage 
```
=================================================================
==1691==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 12 byte(s) in 1 object(s) allocated from:
    #0 0x7f701a173b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x55659525eb65 in OpenMP4Source /home/brandon/PhD/PhD/gpmf-parsergcc/demo/GPMF_mp4reader.c:331
    #2 0x556595233e37 in main /home/brandon/PhD/PhD/gpmf-parsergcc/demo/GPMF_demo.c:48
    #3 0x7f7019cc5b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: 12 byte(s) leaked in 1 allocation(s).
```
2. Use of double-free
```
=================================================================
==3983==ERROR: AddressSanitizer: attempting double-free on 0x602000000030 in thread T0:
    #0 0x7fae182e17b8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8)
    #1 0x560676265322 in CloseSource /home/brandon/PhD/PhD/gpmf-parsergcc/demo/GPMF_mp4reader.c:741
    #2 0x560676262b6a in OpenMP4Source /home/brandon/PhD/PhD/gpmf-parsergcc/demo/GPMF_mp4reader.c:497
    #3 0x560676235e37 in main /home/brandon/PhD/PhD/gpmf-parsergcc/demo/GPMF_demo.c:48
    #4 0x7fae17e33b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #5 0x560676235b69 in _start (/home/brandon/PhD/PhD/gpmf-parsergcc/demo/gpmfdemogcc+0x1b69)

0x602000000030 is located 0 bytes inside of 8-byte region [0x602000000030,0x602000000038)
freed by thread T0 here:
    #0 0x7fae182e17b8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8)
    #1 0x560676262191 in OpenMP4Source /home/brandon/PhD/PhD/gpmf-parsergcc/demo/GPMF_mp4reader.c:431
    #2 0x560676235e37 in main /home/brandon/PhD/PhD/gpmf-parsergcc/demo/GPMF_demo.c:48
    #3 0x7fae17e33b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

previously allocated by thread T0 here:
    #0 0x7fae182e1b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x5606762621e4 in OpenMP4Source /home/brandon/PhD/PhD/gpmf-parsergcc/demo/GPMF_mp4reader.c:434
    #2 0x560676235e37 in main /home/brandon/PhD/PhD/gpmf-parsergcc/demo/GPMF_demo.c:48
    #3 0x7fae17e33b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: double-free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8) in __interceptor_free
==3983==ABORTING
```

I did edit the source code and used a simple workaround, and I hope that the following might help to speed up the fixing of the repo code.

Line 375:
```diff
- if (mp4->metasizes) free(mp4->metasizes);
+ if (mp4->metasizes) free(mp4->metasizes),mp4->metasizes=0;
```

Line 431:
```diff
- if (mp4->metaoffsets) free(mp4->metaoffsets);
+ if (mp4->metaoffsets) free(mp4->metaoffsets), mp4->metaoffsets=0;
```

Line 734 (`void CloseSource(size_t handle)`):
```diff
        mp4object *mp4 = (mp4object *)handle;
        if (mp4 == NULL) return;

        if (mp4->mediafp) fclose(mp4->mediafp), mp4->mediafp = NULL;
        if (mp4->metasizes) free(mp4->metasizes), mp4->metasizes = 0;
        if (mp4->metaoffsets) free(mp4->metaoffsets), mp4->metaoffsets = 0;
+       if (mp4->metastsc) free(mp4->metastsc),  mp4->metastsc = 0;

        free(mp4);
```

There might be other instances that these crashes may occur but the ones mentioned above are those that occurred on my current system.

POCs are attached for debugging:
[LatestPOC.zip](https://github.com/gopro/gpmf-parser/files/3559048/LatestPOC.zip)

**Comment by dnewman-gpsw** [comment]
Thank you.  I pushed these fixes onto both the develop and master branches.
